# Rename this file to .lando.yml to use, or delete if you already have one.
# Named start.lando.yml to not conflict with projects installed with lando mw install.

# project_code: cmm, apb_d7, etc.
name: jcc

# drupal8 | drupal7 | wordpress
recipe: drupal8

config:
  # default: web | lightning: docroot
  webroot: web

  php: '7.3'

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  #xdebug: true


  # *********************************************************************************
  # ****   No need to change anything below, unless you know what you're doing.  ****
  # ****                    And have a very specific need.                       ****
  #**********************************************************************************

# Additional services and features.
services:
  # Theme.
  node-cli:
    type: node:10
    globals:
      gulp-cli: "latest"

# Custom Lando commands
tooling:
  node:
    service: node-cli
  npm:
    service: node-cli
  reset:
    service: appserver
    description: "Runs updb, cr, cim, uli \n Reset your local after a build or db install."
    cmd:
      - drush updb -y
      - drush cr
      - drush cim -y
