display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        media_bulk_form:
          action_title: Action
        thumbnail__target_id:
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: Type
          separator: ', '
        uid:
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_true: Published
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: Operations
      filters:
        bundle:
          expose:
            label: Type
        status:
          group_info:
            group_items:
              1:
                title: Published
        langcode:
          expose:
            label: Language
