display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
      fields:
        state:
          label: Estado
          separator: ', '
        label:
          label: Etiqueta
        source_language_1:
          label: From
          separator: ', '
        target_language:
          label: To
          separator: ', '
        translator:
          label: Proveedor
        progress:
          label: Progreso
        word_count:
          label: Palabras
        tags_count:
          label: Etiquetas
        changed:
          label: Modificado
        operations:
          label: Operations
      filters:
        state:
          expose:
            label: Estado
        source_language:
          expose:
            label: 'Idioma de origen'
        translator:
          expose:
            label: Proveedor
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Empleos
      tab_options:
        title: Empleos
