display:
  default:
    display_options:
      fields:
        state:
          label: Estado
        label:
          label: Etiqueta
        translator:
          label: Proveedor
        progress:
          label: Progreso
        word_count:
          label: Palabras
        tags_count:
          label: Etiquetas
        changed:
          label: Modificado
      filters:
        state:
          expose:
            label: Estado
        source_language:
          expose:
            label: 'Idioma de origen'
        translator:
          expose:
            label: Proveedor
  page_1:
    display_options:
      menu:
        title: Empleos
      tab_options:
        title: Empleos
