display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        state:
          label: Estado
        label:
          label: Etiqueta
        target_language:
          label: Para
        progress:
          label: Progreso
        word_count:
          label: Palabra
        tags_count:
          label: Etiquetas
        changed:
          label: Modificado
        operations:
          label: Operaciones
      filters:
        state:
          expose:
            label: Estados
          group_info:
            label: Estado
        source_language:
          expose:
            label: 'Idioma de origen'
        job_type:
          group_info:
            label: 'Tipo de empleo'
