display:
  default:
    display_options:
      fields:
        state:
          label: Estado
        label:
          label: Etiqueta
        progress:
          label: Progreso
        word_count:
          label: Palabra
        tags_count:
          label: Etiquetas
        changed:
          label: Modificado
      filters:
        state:
          expose:
            label: Estados
          group_info:
            label: Estado
        source_language:
          expose:
            label: 'Idioma de origen'
        job_type:
          group_info:
            label: 'Tipo de empleo'
