display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reset
      filters:
        redirect_redirect__uri:
          expose:
            label: Para
