display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reset
      fields:
        type:
          label: 'Tipo de contenido'
        status:
          label: Estado
        operations:
          label: Operaciones
      filters:
        type:
          expose:
            label: 'Tipo de contenido'
        status:
          expose:
            label: Estado
        langcode:
          expose:
            label: Idioma
