display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        state:
          label: Estado
        label:
          label: Etiqueta
        progress:
          label: Progreso
        word_count:
          label: Palabras
        tags_count:
          label: Etiquetas
        changed:
          label: Modificado
        operations:
          label: Operaciones
  checkout:
    display_title: 'Tramitar compra'
    display_options:
      fields:
        label:
          label: Etiqueta
        word_count:
          label: Palabras
        changed:
          label: Modificado
  submitted:
    display_title: Enviado
