display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        nothing:
          alter:
            text: Editar
        dropbutton:
          label: Operaciones
