display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        label:
          label: Elemento
      title: Mensajes
  embed:
    display_title: Incrustar
