display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          label: Title
          separator: ', '
        type:
          label: Type
          separator: ', '
        status:
          label: Published
          separator: ', '
        name:
          separator: ', '
        changed:
          separator: ', '
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: Type
        status:
          expose:
            label: Published
  block_1:
    display_options:
      pager:
        options:
          tags:
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      filters:
        status:
          expose:
            label: Published
      fields:
        title:
          label: Title
          separator: ', '
        type:
          label: Type
          separator: ', '
        name:
          separator: ', '
        changed:
          separator: ', '
