display:
  default:
    display_options:
      fields:
        state:
          label: Estado
        label:
          label: Etiqueta
        progress:
          label: Progreso
        word_count:
          label: Palabras
        tags_count:
          label: Etiquetas
        changed:
          label: Modificado
  checkout:
    display_title: 'Tramitar compra'
    display_options:
      fields:
        label:
          label: Etiqueta
        word_count:
          label: Palabras
        changed:
          label: Modificado
  submitted:
    display_title: Enviado
