settings:
  default_form_close_message: 'Sorry&hellip; This form is closed to new submissions.'
  default_wizard_prev_button_label: '< Previous'
  default_wizard_next_button_label: Next
  default_wizard_toggle_show_label: 'Show All'
  default_wizard_toggle_hide_label: 'Hide All'
  default_preview_prev_button_label: '< Previous'
  default_preview_message: 'Please review your submission. Your submission is not complete until you press the &quot;Submit&quot; button!'
mail:
  default_from_name: selfhelp.courts.ca.gov
  default_subject: 'Webform submission on page: [webform_submission:source-title]'
  default_body_text: "Submitted on [webform_submission:created]\r\nSubmitted by: [webform_submission:user]\r\n\r\nSubmitted values are:\r\n[webform_submission:source-title]\r\n[webform_submission:values]\r\n"
  default_body_html: "<p>Submitted on [webform_submission:created]</p>\r\n<p>Submitted by: [webform_submission:user]</p>\r\n<p>Submitted values are:</p>\r\n<p>Page: [webform_submission:source-title]</p>\r\n<p>[webform_submission:values]</p>\r\n\r\n"
