favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
facebook: ''
flickr: ''
linkedin: ''
twitter: 'https://twitter.com/CalCourts'
youtube: 'https://www.youtube.com/user/CaliforniaCourts'
