_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - media
  - node
  - taxonomy_term
track_enabled_source_entity_types:
  - access_token
  - node
  - content_moderation_state
  - crop
  - block_content
  - menu_link_content
  - entity_embed_fake_entity
  - fillpdf_file_context
  - fillpdf_form
  - fillpdf_form_field
  - jcc_category
  - jcc_form_thumbnail
  - jcc_prefix
  - jcc_thumbnail
  - media
  - paragraph
  - redirect
  - search_api_task
  - shortcut
  - xlsx_data
  - taxonomy_term
  - tmgmt_job
  - tmgmt_job_item
  - tmgmt_message
  - tmgmt_remote
  - path_alias
  - cc_user_input
  - webform_submission
track_enabled_target_entity_types:
  - access_token
  - node
  - content_moderation_state
  - crop
  - block_content
  - menu_link_content
  - entity_embed_fake_entity
  - fillpdf_file_context
  - fillpdf_form
  - fillpdf_form_field
  - jcc_category
  - jcc_form_thumbnail
  - jcc_prefix
  - jcc_thumbnail
  - media
  - paragraph
  - redirect
  - search_api_task
  - shortcut
  - xlsx_data
  - taxonomy_term
  - tmgmt_job
  - tmgmt_job_item
  - tmgmt_message
  - tmgmt_remote
  - path_alias
  - cc_user_input
  - webform_submission
track_enabled_plugins:
  - block_field
  - ckeditor_image
  - dynamic_entity_reference
  - entity_embed
  - entity_reference
  - html_link
  - layout_builder
  - link
  - linkit
  - media_embed
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types: {  }
usage_controller_items_per_page: 25
