form_settings:
  block_content:
    default_value: true
    disable: true
    hidden: true
  cc_user_input:
    default_value: true
    disable: true
    hidden: true
  crop:
    hidden: true
    default_value: false
    disable: false
  entity_embed_fake_entity:
    hidden: true
    default_value: false
    disable: false
  file:
    disable: true
    hidden: true
    default_value: false
  media:
    disable: true
    hidden: true
    default_value: false
  path_alias:
    hidden: true
    default_value: false
    disable: false
  redirect:
    hidden: true
    default_value: false
    disable: false
  search_api_task:
    hidden: true
    default_value: false
    disable: false
  shortcut:
    hidden: true
    default_value: false
    disable: false
  taxonomy_term:
    disable: true
    hidden: true
    default_value: false
  user:
    hidden: true
    default_value: false
    disable: false
  menu_link_content:
    default_value: true
    disable: true
    hidden: true
  paragraph:
    default_value: true
    disable: true
    hidden: true
  access_token:
    default_value: false
    disable: false
    hidden: false
  content_moderation_state:
    default_value: false
    disable: false
    hidden: false
  node:
    default_value: false
    disable: false
    hidden: false
  webform_submission:
    default_value: false
    disable: false
    hidden: false
  jcc_form_thumbnail:
    default_value: false
    disable: false
    hidden: false
  jcc_category:
    default_value: false
    disable: false
    hidden: false
  jcc_prefix:
    default_value: false
    disable: false
    hidden: false
  jcc_thumbnail:
    default_value: false
    disable: false
    hidden: false
  xlsx_data:
    default_value: false
    disable: false
    hidden: false
