_core:
  default_config_hash: IGXEOM4wHQhsKaCjAxgt-leFoP9014Gb7CQ-M2tSe8w
backend: local_service
remote_protocol: https
remote_endpoint: fillpdf.io/xmlrpc.php
allowed_schemes:
  - private
template_scheme: public
local_service_endpoint: 'https://jcc-fillpdf.azurewebsites.net'
shell_locale: en_US.UTF-8
