helpfulness_yes_title: "<p>Thanks. Any other comments?</p>\r\n"
helpfulness_yes_description: "<p>We appreciate the feedback.</p>\r\n"
helpfulness_no_title: "<p>Sorry to hear that. Please tell me more!</p>\r\n"
helpfulness_no_description: "<p>Please include your email if you want us to follow up with you.</p>\r\n"
helpfulness_comment_required: '1'
helpfulness_comment_required_message: 'Comment is required.'
helpfulness_notification_email: ''
helpfulness_notification_subject: null
helpfulness_notification_message_prefix: 'You have received new helpfulness feedback.'
helpfulness_report_option_display_username: 0
helpfulness_report_option_display_helpfulness: 1
helpfulness_report_option_display_message: 1
helpfulness_report_option_display_base_url: 0
helpfulness_report_option_display_system_path: 1
helpfulness_report_option_display_alias: 0
helpfulness_report_option_display_date: 1
helpfulness_report_option_display_time: 0
helpfulness_report_option_display_useragent: 0
_core:
  default_config_hash: hQEIPXqawKNo6Y7nOnCSo0mqbR5d1npxXRKZnZ4LdaM
