_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    ru: ru
    ko: ko
    pa: pa
    fil: fil
    ar: ar
    fa: fa
    zh-hans: zh-hans
    vi: vi
    zh-hant: zh-hant
  domains:
    en: ''
    es: ''
    ru: ''
    ko: ''
    pa: ''
    fil: ''
    ar: ''
    fa: ''
    zh-hans: ''
    vi: ''
    zh-hant: ''
selected_langcode: site_default
